model_path: "/cluster/work/igp_psr/dslab_FS25_data_and_weights/models/model_2025-05-01-14-35-02/"


# evaluation period
same_day_as_training: true
year: 2024
start_doy: 100
num_days: 1


# one of regular, SA 
evaluation_data: "SA"
sa_path: "/cluster/work/igp_psr/dslab_FS25_data_and_weights/arno/sa_dataset.csv"