# training params
learning_rate: 0.001
batch_size: 8192 #4092
epochs: 10
num_workers: 16
pytables: false # make sure to set to True when running locally or in login node
optional_features:
  initial:
  #  - "doy"
  #  - "year"
   - "kp_index"
   - "r_index"
   - "dst_index"
   - "f_index"
  delayed:
   - "doy"
   - "year"
  #  - "kp_index"
  #  - "r_index"
  #  - "dst_index"
  #  - "f_index"

# model params
pretrained_model_path: null

model_type: "TwoStageModel"
training_loss: "MAE"
num_hidden_layers_1: 4
hidden_size_1: 256
output_size_1: 256
num_hidden_layers_2: 2
hidden_size_2: 256 # not used

# model_type: "FCN"
# num_hidden_layers: 6
# hidden_size: 256


# time period
years:
  2022: "all"
  2023: "all"
  2024: [1,2,3,4,5,6]

# paths
use_reorganized_data: true
datapath: "/cluster/work/igp_psr/arrueegg/GNSS_STEC_DB/"
dslab_path: "/cluster/work/igp_psr/dslab_FS25_data_and_weights/"
models_dir_name: "pretrained_models"
# reorganized_data_dir_name: "reorganized_data_4" # 4 -> daily solar indices
reorganized_data_dir_name: "reorganized_data_5" # 5 -> hourly solar indices