# training params
learning_rate: 0.001
batch_size: 262144
epochs: 10
num_workers: 4
pytables: false

# model params
pretrained_model_path: null
model_type: "FCN"
num_hidden_layers: 1
hidden_size: 256

# time period
years:
  2022: "all"
  2023: "all"
  2024: "all"

# paths
use_reorganized_data: true
dslab_path: "/cluster/work/igp_psr/dslab_FS25_data_and_weights/"
models_dir_name: "pretrained_models"
reorganized_data_dir_name: "reorganized_data_2"