# Config file for run_training.py in order to pretrain models 
# on reorganized data corresponding to a large period of time.

# training params
learning_rate: 0.001
batch_size: 8192 
epochs: 10
num_workers: 16
# Whether to use pytables (true) or bring data to main memory (false)
# Make sure to set to true when running locally or in login node, out of memory errors may happen otherwise
# Set to false when running on the cluster for faster trainings.
pytables: false 
optional_features:
   - "doy"
   - "year"
   - "kp_index_hourly"
   - "r_index_hourly"
   - "dst_index_hourly"
   - "f_index_hourly"
  #  - "kp_index_daily"
  #  - "r_index_daily"
  #  - "dst_index_daily"
  #  - "f_index_daily"


# model params
pretrained_model_path: null


model_type: "TwoStageModel"
training_loss: "MAE"
num_hidden_layers_1: 4
hidden_size_1: 256
output_size_1: 256
num_hidden_layers_2: 2
hidden_size_2: 256


# time period
years:
  2022: "all"
  2023: "all"
  2024: [1,2,3,4,5,6]

# paths
use_reorganized_data: true
datapath: "/cluster/work/igp_psr/arrueegg/GNSS_STEC_DB/"
dslab_path: "/cluster/work/igp_psr/dslab_FS25_data_and_weights/"
solar_indices_path: "/cluster/work/igp_psr/dslab_FS25_data_and_weights/"
models_dir_name: "pretrained_models"
reorganized_data_dir_name: "reorganized_data_2"