# Config file for reorganizing the dataset, separating training, validation and testing data and subsampling it.

datapath: "/cluster/work/igp_psr/arrueegg/GNSS_STEC_DB/"
dslab_path: "/cluster/work/igp_psr/dslab_FS25_data_and_weights/"
output_dir_name: "reorganized_data_subsampled"

# reorganized data is subsample in time by this factor
subsampling_ratio: 0.02

# for each year, specify either "all" or a list of months e.g [10, 11, 12]
years:
  2022: "all"
  2023: "all"
  2024: "all"
