datapath: "/cluster/work/igp_psr/arrueegg/GNSS_STEC_DB/"
dslab_path: "/cluster/work/igp_psr/dslab_FS25_data_and_weights/"
solar_indices_path: "/cluster/work/igp_psr/dslab_FS25_data_and_weights/"
solar_indices_mode: "hourly"
output_dir_name: "reorganized_data_5"
years:
  2022: "all"
  2023: "all"
  2024: "all"
subsampling_ratio: 0.02

