datapath: "/cluster/work/igp_psr/arrueegg/GNSS_STEC_DB/"
dslab_path: "/cluster/work/igp_psr/dslab_FS25_data_and_weights/"
solar_indices_path: "/cluster/work/igp_psr/dslab_FS25_data_and_weights/"
output_dir_name: "reorganized_data_subsampled"
# output_dir_name: "reorganized_daily_data_hourly_solars"

mode: "months" # or "days"
solar_indices_mode: "hourly"
subsampling_ratio: 0.02

# if using 'months' mode, list all years and corresponding months here
years:
  2022: "all"
  2023: "all"
  2024: "all"

# if using 'days' mode, indicate the year, the first day and the last day (inclusive) that should be reorganized
year: 2024
first_day: 183
last_day: 183 

