# training params
learning_rate: 0.001
batch_size: 1024
epochs: 10
num_workers: 1
pytables: false 
optional_features: []
use_spheric_coords: false
normalize_features: false


pretrained_model_path: null
training_loss: "MAE"

# only relevant when pretrained_model_path is null
model_type: "FCN"
num_hidden_layers: 2
hidden_size: 256

# time period
year: 2024
start_doy: 183
num_days: 1


# paths
use_reorganized_data: false
datapath: "example_code/"
dslab_path: "example_code/"
models_dir_name: "models"
# reorganized_data_dir_name: "reorganized_daily_data_daily_solars"
# reorganized_data_dir_name: "reorganized_daily_data_hourly_solars"
solar_indices_path: "/cluster/work/igp_psr/dslab_FS25_data_and_weights/"