# training params
learning_rate: 0.001
batch_size: 262144
num_workers: 4
epochs: 10

# model params
model_type: "FCN"
num_hidden_layers: 1
hidden_size: 256

# time period
year: 2024
start_doy: 1
num_days: 10

# global variables
datapath: "/cluster/work/igp_psr/arrueegg/GNSS_STEC_DB/"
dslab_path: "/cluster/work/igp_psr/dslab_FS25_data_and_weights/"
